### ISSUE TITLE
Some misunderstandings

### ISSUE THREAD

**Issue by xdlequ** [benedekrozemberczki/ASNE#1]
Hello, the author. I am very happy to find your implementation of the ASNE method on github, but I have a question. The illustrations in your readme file are not in the article. Excuse me, this part is not your own mistake.  I hope to get a reply in time. Thank you

**Comment by benedekrozemberczki** [comment]
Hi there,

I created a general plot to explain attributed embedding techniques. It is the plot that you see in the repo. I used the same plot in:

https://github.com/benedekrozemberczki/TENE
https://github.com/benedekrozemberczki/FSCNMF
https://github.com/benedekrozemberczki/TADW

If You have a more informative high definition image I am very happy to change the plot in the repository.
