### ISSUE TITLE
predict function

### ISSUE THREAD

**Issue by ARNABKUMARPAN** [benedekrozemberczki/ASNE#2]
can you please provide the predict function?

**Comment by benedekrozemberczki** [comment]
?

**Comment by ARNABKUMARPAN** [comment]
Hello,
How to use the embedding that you have generated for link prediction? Is
there any implementation of that? I am new in node embeddings. I will be
very happy if you kindly provide me the understanding along with code.
Thanks and Regards
Arnab

**Comment by benedekrozemberczki** [comment]
1. You have to create a corrupted graph by removing edges, but maintaining the number of connected components. The removed edges are positive cases.
2.  You have to create an embedding of the corrupted graph.
3.  You have to create a new graph where there are additional fake edges. The fake edges are negative cases.
4. Calculate for each edge in the augmented graph using the embedding of the attenuated graph the representation -- use binary operators described in Node2Vec. This is the work of (Grover and Leskovec , 2016).
